### ISSUE TITLE
♻️ Move [Handler] attribute from class, to method

### ISSUE THREAD

**Issue by Hona** [viceroypenguin/Immediate.Handlers#48]
It feels a little less cohesive if the [Handler] attribute.

It would be cool to change the code a bit

```cs
// [Handler] ❌ Delete this
public sealed partial class GetAllTodosQuery
{
    public sealed record Query(bool? IsCompleted = null);

    [Handler] // ✅ New code
    private static async ValueTask<IReadOnlyList<Todo>> HandleAsync(Query request, AppDbContext dbContext, CancellationToken cancellationToken)
    {
        var todos = await dbContext.Todos
            .Where(x => request.IsCompleted == null || x.IsCompleted == request.IsCompleted)
            .ToListAsync(cancellationToken);

        return todos.AsReadOnly();
    }
}
```

**Comment by Hona** [comment]
I'm unsure if there are constraints around source gens though

**Comment by viceroypenguin** [comment]
This would raise additional complexity for the consumer:
* there is now one more place that `[Behaviors]` override attribute could go
* there is potentially more confusion when you can only apply `[Handler]` on a `Handle`/`HandleAsync` method (but I want to add `HandleXxxAsync`)
* there is potentially more confusion when you can only apply `[Handler]` to a _single_ method in the class (but I want to add `HandleXxxAsync` and `HandleYyyAsync`)
* once you get used to it, it starts to make sense that `[Handle]` is a part of the class, because the `.Handler` class gets added as part of the class, not the method. the whole class is built around being a handler.

**Comment by Hona** [comment]
Fair points! :)
